<?PHP

include('inc/html_header.php');

?>
<table id="tableContent" cellspacing="0" cellpadding="0">

<tr>
 <td class="columnTitleLeft"><h1>Donna Leishman</h1></td>
 <td>&nbsp;</td>
 <td class="columnTitleRight"><h1>Jason Nelson</h1></td>
</tr>

<tr>

<td class="columnLeft">

  <!-- left column content -->
  <h2>Navigation, Investigation, and Inference: Donna Leishman's <i>Deviant: The Possession of Christian Shaw</i>, by Talan Memmott</h2>
  <p>A haunting overture plays as we enter a cartoon cityscape. Four tall buildings, a church, some trees.... Seems peaceful enough.... What happens next? Such is the case when one first encounters Donna Leishman's <i>Deviant: The Possession of Christian Shaw</i>&#8212a work of narrative hypermedia that plays with expectations of both narrative and hypermedia.</p>
  <p>The initial screen does not present the user with any obvious links or areas of interaction, but what one soon discovers is that there are links hidden everywhere in the cityscape; you just have to find them. This investigation of the interface seems an important part of the narrative strategy in the work, as will be discussed below.</p>
 <p><i>Deviant: The Possession of Christian Shaw</i> is developed in Macromedia[now Adobe] Flash and was produced as part of Leishman's doctoral thesis. The piece is a retelling of a bit of 17th-century Scottish history. I don't want to give away the base narrative here, because in many ways this would destroy how the work operates, how the narrative unfolds through interactive participation with it. Let's just say the story, as indicated in the title, has something to do with a questionable possession, accusations of witchcraft, and the ramifications of these accusations.</p>
<p>The design of the work is crisp and simple in most regards, and the characters of the story are rendered in a sort of alternative comic style. They are highly stylized. The Christian Shaw character is actually quite endearing with her over-sized head, sad expression, and big eyes. Based on my understanding of the Christian Shaw story, this is something of a sucker punch. The cuteness of the Christian Shaw character builds empathy in defiance of the captivating yet perverse nature of the original story.</p>
<p>The supporting documents of Leishman's thesis&#8212titled Creating Screen-Based Multiple State Environments: Investigating Systems of Confutation&#8212explain in detail many of the aesthetic, poetic, and narrative choices in the work. Even the title of the thesis gives some hint as to what is going on here. To confute is to decisively prove something incorrect. An earlier, now obsolete, definition of the term is to confound. Both of these definitions are very much at play in <i>Deviant</i>. In its retelling of the story, the work questions certain historical facts and, in terms of narrativity, operates in a way that some may find confounding.</p>
<p>From the initial screen&#8212the cityscape&#8212the user, though the author/artist prefers to call the user a participant, is provided access to additional panels. These secondary panels are where the narrative occurs, through animated vignettes that at times can be rather cryptic.</p>
<p>There is very little text in the piece, with most of the interactive and narrative cues occurring visually. These vignettes are pieces of a story, of a puzzle to be realigned, reconfigured by the engaged participant. As such <i>Deviant</i> is not so much a retelling of the Christian Shaw story as an opening-up of the base narrative. From what is implied in the original story, the author/artist has made inferences and made vignettes of these inferences. It is the job of the participant to take what is now implied in the vignettes and draw their own inferences from this. The process is quite cunning as the narrative is now twice removed from its source, rendered almost irrelevant to the participant. Without some prior knowledge of the Christian Shaw story, it would be difficult to place the narrative generated through interaction with the piece as a 17th-century factually-based Scottish tale. The characters are not costumed in this period, and certainly the architecture of the cityscape is anachronistic. There is a continuation of inferability without referability back to the base narrative. In this regard the user is a participant in the narrative construction of the piece and is not so much asked to read the vignettes as write out of them.</p>
<p>There are a couple of terms introduced in the supporting thesis that I think deserve mentioning, as they directly relate to the author/artist's narrative intentions. In the thesis Leishman uses the term <i>digressive spaces</i> to describe the vignettes that are accessed from the central cityscape.</p>
<p>In <i>Deviant</i> this term is realized in a number of ways. First, some of the vignettes include rather detailed animations that are not necessarily additive in terms of narrative. In one vignette we are treated to falling flower petals when we move the cursor over the flower graphics. In another, the leaves of a tree change colors upon mouseover allowing the participant to construct patterns in the foliage. Neither of these examples adds much to the narrative; rather, they are momentary digressions, reprieves from the narrative that could be considered bits of visual poetry. On more than one occasion I caught myself dwelling on the construction of patterns in the tree foliage. The term <i>digressive spaces</i> could be employed in another area of the work. The piece is nonlinear and variable, though it does possess an explanatory epilogue of sorts. After repeated visits to the work, I found myself interested in certain vignettes, learning the navigational patterns it takes to reveal them. This feature in itself is digressive, in that it works somewhat against the generation of a consistent and cohesive narrative for the work.</p>
<p>Certainly, within literary hypermedia, variability is a key consideration, but with <i>Deviant</i> the variability is somewhat controllable if patterns of interactivity are learned by the participant. This sort of play with the interface adds another layer of complexity to the whole as it introduces an aspect of gaming into the overall piece.</p>
<p>This playful aspect is reinforced by the method of navigation one vignette to another. When a vignette has been closed the participant is returned to the cityscape, but the cityscape has been transformed. Something has changed. In most cases tiny navigation points are added to the cityscape providing access to additional vignettes, though it may take a moment to find these. This sort of "Where's Waldo?" metaphor&#8212the tiny navigation points that require investigation of the interface to be discovered&#8212leads to the second term from the thesis that I would like to mention, <i>atmospheric accumulation</i>. I think this term applies to both the cityscape interface and the <i>digressive</i>  (though narrative) <i>spaces</i> of the vignettes.</p>
<p>As stated above <i>Deviant</i> seems less about readability than inferability. The participant is just that&#8212a participant in the narrativity, or narra[c]tivity of the work. The interface and its navigational cues perform and require a sort of environmental grammatology. We construct a story, our own story out of the fragments of the world we are presented with. In this regard, <i>Deviant</i>  is an open narrative structure that is not burdened with expectations of clarity or understanding of writerly intent. These are things left to the participant.</p>
<p>I would urge any user/participant to explore the piece: invent and enjoy before doing any research into the story of Christian Shaw. If you happen to come to the epilogue during your first exploration of the piece, ignore it and go through the piece one more time. Certainly, at some point, it is a good idea to read the epilogue to come to some understanding of the base narrative, but part of the joy of Leishman's <i>Deviant</i>  is in the potential deviations from the original story.</p>
</td>

<? include ('inc/html_options.php'); ?>

<td class="columnRight">

  <!-- right column content -->
  <h2>Clutteralist Aesthetics and the Poetics of Whimsy: The Work of Jason Nelson, by Talan Memmott</h2>
<p>There is something incredibly consistent about Jason Nelson's hypermedia work. <i>Something</i>, yes, but it is hard to put your finger on that something. It is not that the works look the same, though they are recognizably Nelson works. And, there are themes and preoccupations that are repeated, populating a number of the author's works, but the utterances, one application to the next, are not posited as repetitions but as separate iterations, remediations of certain themes that lead to different sorts of interfaces and interactions, different modes and methods of signification. As such, the consistency has more to do with attitude and approach than content.</p>
 <p>Nelson's  <i>digital creatures</i>, as he calls them at his <i>secret technology</i> website (<a href="http://www.secrettechnology.com" target="_new">http://www.secrettechnology.com</a>), are indeed odd applications. Like most creative hypermedia work they don't rest comfortably as one thing or another&#8212they are not applications with an explicit use-value and they take some time to get to know. The works could be defined as poetry (sometimes), narrative (sometimes), interactive art (sometimes), or any mix of the above. In this regard, they are what they are&#8212creative expression through technology: digital <i>creatures</i>.</p>
  <p>Many of the interfaces for the various works operate in such a way as to&#8212perhaps intentionally&#8212mitigate the subjects of the work. Or, perhaps the mitigation is the content. One could call the design method here messy, and sometimes the applications seem fragile or touchy, maybe rickety. In calling the design messy, or the applications rickety, I in no way mean to imply that they are faulty. These attributes seem rather intentional and strategic. There is a blend of overload and reload in the work&#8212the reload of common themes (death being the most common) and overload in terms of the use of media and their signifying properties.</p>
  <p>An example of these methods can be found in Nelson's  <i>Promiscuous Design</i>. The interface of this work is made up of what appear to be illustrations culled from a child's encyclopedia. Various races are represented, agrarian and industrial work flows, dairy cattle, and manufacturing. On the right side of the interface we find two headings, <i>Channels</i> and <i>Frequencies</i>.</p>
  <p>The <i>Channels</i> heading provides access to six checkboxes with somewhat cryptic titles&#8212<i>pandemic affairs, marketing god and trees, felonious colors, some past travel fails, analogous to stuttering</i>, and <i>if broadcasts were boats</i>&#8212and we initially have no idea what any of this may mean or what will happen when any of these boxes are checked. The <i>Frequencies</i> heading is below and is made up of a field of a dozen square buttons surrounding a field of five similar buttons. To a certain extent the interface is about inducing the user to activate these cryptic areas. And, once one does engage with these elements, the piece begins to open up.</p>
 <p>Moving the cursor over the outside <i>Frequencies</i> buttons initiates an audio file that says "Shush." Clicking on the buttons plays additional audio files, sometimes adding diagrams or video to the general interface. The central <i>Frequencies</i> buttons, which are labeled "disrupt" upon mouse over, operate in a similar fashion, but here when the user moves the cursor over the added diagrams the interface is complicated by texts of some length, though mostly unreadable and sometimes rendered in reverse.</p>
<p>Checking any of the <i>Channels</i> checkboxes layers various words&#8212<i>law, culture, the keel</i> to name a few&#8212on top of the encyclopedia illustrations. Moving the cursor over these added words changes the word&#8212<i>law</i> becomes <i>flightless,  the keel</i> becomes <i>the boat</i>&#8212and pops up a short poetic or critical text.</p>
<p>One of the texts that appear when the cursor is over  the keel is quite telling as to what is being explored in the work:</p>
<p><i>We create artificial understandings, unreal meanings for our surroundings. Our diagrams map relationships to fit whichever mode we fancy. This work mirrors those false categories, the absurd and nearly random divisions.</i></p>
<p>In addition to the layering and altering of words and text, the <i>Channels</i> checkboxes add hand-drawn arrows onto the illustration, sometimes connecting words with images, sometimes connecting one illustration to another. Checking the box for <i>felonious</i> colors not only adds the word <i>law</i> to the interface but also produces circles and lines connecting the illustration of an agrarian worker to that of a manufacturing worker, and the manufacturing worker to a commercial product.</p>
<p>These hand-drawn lines and arrows are sometimes employed to scratch out certain words or parts of words creating palimpsests that disrupt assumed meaning or increase potential meaning. The title of the piece itself is altered in this way. Appropriately, <i>Promiscuous Design</i> becomes <i>Promiscuous Design</i>...which is what we have here, promiscuous signs, a metaphoric display of the semiotic process. Or, a semiotics of semiotics.</p>
<p>Looking through Jason Nelson's catalog of work there are two things that definitely stand out, his willingness to consider the work incomplete&#8212to let works go through various iterations&#8212and a creative repurposing of appropriated code. His works <i>Dreamaphage</i> and <i>this will be the end of you</i> have both gone through a number of iterations, each very different from the other. The appropriation and repurposing of code, mostly actionscript for Macromedia[now Adobe] Flash, is evident throughout his catalog.</p>
<p>In Nelson's <i>The Bomar Gene</i> we find the well-known memory game  <i>Concentration</i> repurposed as an embodied narrative device. The game is set alongside a ficto-biographical story that tells of an elderly woman who has collected photographs throughout her life and now has "hundreds of thousands of photographs pasted, glued, tacked to the walls and ceiling and floor" of her two-bedroom house, "each photograph...connected to another, lines of yarn or thin nylon cord connecting the pair." Connecting one photograph with its partner is what occurs in the game. In effect, the user mirrors the acts of the protagonist of the story by playing the game.</p>
<p>Other areas of <i>The Bomar Gene</i> include the coupling of a story of a mentally ill child and her art therapist with a color picker application, and the story of a young man with a propensity for numbers coupled with a pixel plotting array. Throughout this work we find this sort of appropriation and repurposing of fairly common Flash applications, here used as embodied narrative devices that extend the premises of the text-based stories.</p>
<p>Nelson's recent <i>This Is How You Will Die</i> is another fine example of this repurposing method. With this work the user is presented with an interface that mixes metaphors of game play, gambling, chance, fate, and divination. Set to a rather eerie soundtrack, the piece borrows from the devices of a slot machine, here called the death spin. As with a slot machine the user engages five spinning wheels, but rather than the traditional cherries, oranges, and lemons these wheels contain short fragments of text that when read in conjunction with one another predict the user's death.</p>
<p>An example of a potential combination of texts reads:</p>
<p><i>Searching for your breakthrough poetry manuscript thrown out "accidentally", | a vagrant mistakes you for a 'parking lot god' and worships you with knives, | at least, for a few minutes you have given someone a defining purpose. | Instead of dieing completely, you fall into the middle space, space between molecules | Your ghost, specter, spirit, or banshee wanders confused until the sun explodes.</i></p>
<p>As the user continues to spin, demise points are added or taken away. Once the user's score drops below 10 play is stopped.</p>
<p>This piece rests somewhere between the oracular and the vernacular. In its use of a gambling metaphor it both makes points about life being based in chance and minimizes the direness of the question, <i>when and how will I die?</i> It is interesting for its combination of high and low concerns and demonstrates a rather conscientious appropriation of an application meant purely for entertainment, repurposing the application as something mysterious and quite poetic.</p>
<p>All in all, when we experience Jason Nelson works we are asked to take a leap, to read beyond reading, to look and listen and do. These works are born digital and rarely backtrack historically to moments before multi-modal new media signification. Perhaps then, they are works to be operated rather than read (in the strict sense). They are playful yet serious, demonstrative yet subtle, experimental yet realized. Mostly, though, they are good fun.</p>
</td>

</tr>
<? include('inc/html_copyright.php') ?>
</table>
<?

include('inc/html_footer.php');

