<?PHP

include('inc/html_header.php');

?>
<table id="tableContent" cellspacing="0" cellpadding="0">

<tr>
 <td class="columnTitleLeft"><h1>Donna Leishman</h1></td>
 <td>&nbsp;</td>
 <td class="columnTitleRight"><h1>Jason Nelson</h1></td>
</tr>

<tr>

<td class="columnLeft">

  <!-- left column content -->
  <h2>What kind of reception/recipient do your e-texts need? Do you have a sense of "making room for someone else," or do you rather aim to "compel an encounter"? How much does the reader/user need to know, about you, about digital lit, about your themes?</h2>
  <p>My work needs someone who likes to reflect and who has an enquiring mind. The work quickly presents itself as something "other" than the quick fire or instant gratification of many modern-day visual communications. Instead, I hope it is simultaneously visually alluring and difficult in terms of reaching clear understandings of the narrative. I have both a sense of making for someone else (a notional female) and needing to compel an encounter that is emotional. The user doesn't need to know about me or digital literature per se; in fact, knowing less about the latter may help their immersion, in that their experience would have immediacy, rather than anticipating how post-structuralism or reader-response theories fit my work. I hope the unraveling themes I use are suitably rich for the user to absorb, even if the projects are only partly explored.</p>

</td>

<?php include ('inc/html_options.php'); ?>

<td class="columnRight">

  <!-- right column content -->
  <h2><strong>What kind of reception/recipient do your e-texts need? Do you have a sense of "making room for someone else," or do you rather aim to "compel an encounter"? How much does the reader/user need to know, about you, about digital lit, about your themes?</strong></h2>
  <p>Unfortunately, I've been experimenting with creating title html pages for my work, explanatory bits to help the user into the experience. I say unfortunately, because I usually loathe prefacing my work, forecasting the user experience. Much like not watching the previews before you see a movie. I enjoy the unexpected, that sense of the dark, dark, the hidden light switch that opens the bookcase to a circling descent, instead of the expected illuminating. But enough confused readers have missed even entering the work properly, or been diverted by perceived tech troubles, to convince me to offer more direction, to hold their hand a bit while they explore for the first time.</p>
  <p>Perhaps one of the strongest draws many find for e-lit is its relative lack of rules, existing forms, or established meanings and methods. It is quite freeing as an artist to simply explore one's imagination and texts with only technical constraints limiting the possible creatures birthed.</p>
  <p>However, once the critter is forced to breathe, would there be some puppy cuteness attached to its face to make people love it? I suppose the relative newness (20,000 [years] for poetry, around 50 more or less for electronic bits) of the form requires some teaching of the user/reader. But some of the awe, and user ownership, created by raw exploration is lost with directions, or even titles. For example the title, <i>This Is How You Will Die,</i> clearly directs the reader to a rather foreboding and slightly creepy conclusion. So I struggle with this notion of titles. Some are obvious: <i>Nine Attempts To Clone A Poem</i>; some are place or person oriented: <i>Panhandle</i> or <i>The Bomar Gene</i>; and others are more theory/architecture driven like <i>Uncontrollable Semantics</i> or <i>Promiscuous Design.</i></p>
  <div><a href="images/content/nelsonreception.jpg" target="_new"><img src="images/content/thumbs/nelsonreception.jpg" /></a></div>
  <p>From Hermeticon</p>
  <p>Another loss generated by descriptions and directions is the loss of sloppiness. We are all sloppy, messy animals. Our worlds have frayed skins. Tech work can tend to appear polished, and academically driven descriptions constrain the work to certain intentions and goals. But perhaps what we need more of, in digital lit, is sloppiness and a sense of disorganization, of the way our worlds really function. My work <i>Promiscuous Design</i> is really a commentary on exactly this idea. I created a work to be a confusing and sloppy mess, to have that mess layered and buildable. There are even directions there, which are confusing as well.</p>
  <pUltimately, I see the reader as an explorer who may or may not persist in revealing all of the work. Every work of mine has an e-mail address hidden deep among the layers. If someone clicks on it and send me an e-mail, I will send them a prize. And every work of mine has other hidden bits: thank you's, porn pictures, me naked, hidden texts, and all that. Some are so well tucked away that even decompiling the swf wouldn't help you much.</p>
  <p>And exploration doesn't have to be in terms of the hidden. It could simply be the movement of the mouse in creating space-scapes. <i>Uncontrollable Semantics</i> is built out of fifty different mouse followers (or likeminded functions). The idea was that the work doesn't exist or function without the user's movement and discovery. I wanted the user/reader to be forced and eventually compelled to play, to feel ownership and artistic ability through their interaction.</p>


</td>

</tr>
<?php include('inc/html_copyright.php') ?>
</table>
<?php

include('inc/html_footer.php');

